---
- name: Collect and save running-config
  hosts: csr
  gather_facts: no
  vars:
    student_id: "{{ student_id | default('66070069') }}"
  tasks:
    - name: Get running-config
      cisco.ios.ios_command:
        commands: ["show running-config"]
      register: run_cfg

    - name: Save running-config locally as show_run_[studentID]_[router_name].txt
      copy:
        content: "{{ run_cfg.stdout[0] }}"
        dest: "show_run_{{ student_id }}_{{ inventory_hostname }}.txt"
        mode: "0644"
      delegate_to: localhost
