---
- name: Collect and save running-config
  hosts: CSR1000V
  gather_facts: false
  connection: ansible.netcommon.network_cli
  collections:
    - cisco.ios
    - ansible.netcommon
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_network_cli_ssh_type: paramiko   # <-- บรรทัดสำคัญ
    student_id: "{{ student_id | default('66070069') }}"
  tasks:
    - name: Get running-config
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: run_cfg
    - name: Ensure local backups folder exists
      delegate_to: localhost
      ansible.builtin.file:
        path: backups
        state: directory
        mode: '0755'
    - name: Save running-config locally
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ run_cfg.stdout[0] }}"
        dest: "backups/show_run_{{ student_id }}_CSR1000V.txt"
        mode: "0644"
